### ISSUE TITLE
[FR] Endorse Flatpak and Snap

### ISSUE THREAD

**Issue by CodeSandwich** [AppFlowy-IO/AppFlowy-Website#28]
### Description

As of now there's no information on the landing page about the official Flatpak image: https://flathub.org/apps/io.appflowy.AppFlowy. It would be great if the dropdown with the different installation ways contained the Flatpak option, it could be just a link to Flathub, people can figure out the installation from there:
![image](https://github.com/AppFlowy-IO/AppFlowy-Website/assets/26183680/452d8f5d-ffd8-4853-81c1-92c8ea6556cd)

I think that it's worth considering to make Flatpak the default option too. I don't want to get into the package flame war, but Flatpak is widely supported (unlike .deb and .rpm that are distro-specific), it supports automatic updates (unlike AppImage and .tar.gz) and it feels the safest to install because it's sandboxed (unlike all the others).

### Impact

Being more welcoming for the Linux users.

**Comment by qinluhe** [comment]
Thanks for your suggestion, we will add these two links to the download options of the button
