### ISSUE TITLE
[Bug] Invalid SSL certificate on website

### ISSUE THREAD

**Issue by CodeShakingSheep** [AppFlowy-IO/AppFlowy-Website#32]
### Bug Description

When visiting https://www.appflowy.io/ it is displayed that the SSL certificate is invalid. 

### How to Reproduce

Just go to https://www.appflowy.io/

### Expected Behavior

SSL certificate should be valid. 

### Operating System

Android

### AppFlowy Version(s)

Website

### Screenshots

![Screenshot_20240118-151204](https://github.com/AppFlowy-IO/AppFlowy-Website/assets/19874562/2046a4b6-9980-4aab-80ba-4882c917965b)

**Comment by qinluhe** [comment]
Does this problem still exist now?

**Comment by CodeShakingSheep** [comment]
Seems to be fixed. No more invalid certificate 👍
